### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by massimiliano-dalcero** [r3nt0n/bopscrk#10]
Hi :) 
Usually I'm not a Windows user, but for a professional task I had to work from a windows computer.

So, I try to use bopscrk from this win computer and when launch the tool from command line (cmd), it terminates at zero time without providing anything in output.

(no problems on Linux)

![image](https://user-images.githubusercontent.com/5049867/97807401-c7d51200-1c60-11eb-84fb-82a8fc25234a.png)

There are some know troubles with windows OS?

Thanks & best regards :)

**Comment by r3nt0n** [comment]
Hi @massimiliano-dalcero ,

Actually, there was a bug with `bopscrk` running on Windows systems (issue #11 ) but it was solved with the last commit. 

Anyway, the problem you described doesn't seem to be related with this one. **In your case, looks like Python is not running**. Please, follow the next steps:

+ In cmd, **execute** `python`
  + If python opens and shows 3.x version, **just run bopscrk this way**: `python bopscrk.py [args]` (instead of `python3`)
  + If python opens and shows 2.x version, **verify your Pyhon version installed, and how your PATH is configured**
  + If python doesn't open, **verify if python is in your PATH**

Please, provide some feedback when you have time to test it. Thanks :+1:
